from enum import Enum

class Role(str, Enum):
    ADMINISTRATOR = "ADMINISTRATOR"
    SECURITY_OFFICER = "SECURITY_OFFICER"
    TRUSTED_OFFICER = "TRUSTED_OFFICER"
    AUDITOR = "AUDITOR"
    STANDARD_USER = "STANDARD_USER"
